### ISSUE TITLE
Don't enable SSE4 always for X64, only on AES functions that require it (for old Atom chips)

### ISSUE THREAD

**Issue by glimberg** [zerotier/ZeroTierOne#1275]
1.5.0 beta crashing on old Intel Atom chips without SSE4

@ogarcia brought this up here on an unrelated issue: https://github.com/zerotier/ZeroTierOne/issues/1272#issuecomment-707641876

backtrace:
```
#0  ZeroTier::AES::_encryptSW (this=0x55581a1b0f20, in=<optimized out>, 
    out="A lot of \nnn chars"...) at node/AES.cpp:1361
#1  0x000055581849ee4b in ZeroTier::AES::_initSW (this=0x55581a1b0f20, key=<optimized out>) at node/AES.cpp:1265
#2  0x0000555818517d0a in ZeroTier::AES::init (this=0x55581a1b0f20, key=0x7ffc89e217f0) at node/AES.hpp:97
#3  ZeroTier::Peer::Peer (this=0x55581a1b0ef0, renv=<optimized out>, myIdentity=..., peerIdentity=...) at node/Peer.cpp:66
#4  0x000055581852866d in ZeroTier::Topology::_memoizeUpstreams (this=<optimized out>, tPtr=<optimized out>) at node/Topology.cpp:373
#5  0x00005558185269f2 in ZeroTier::Topology::addWorld (this=0x7fe9fe4f0f30, tPtr=0x0, newWorld=..., alwaysAcceptNew=<optimized out>) at node/Topology.cpp:275
#6  0x000055581852622d in ZeroTier::Topology::Topology (this=0x7fe9fe4f0f30, renv=<optimized out>, tPtr=0x0) at node/Topology.cpp:41
#7  0x000055581850ce08 in ZeroTier::Node::Node (this=0x7fe9fe4f3010, uptr=<optimized out>, tptr=0x0, callbacks=<optimized out>, now=<optimized out>) at node/Node.cpp:120
#8  0x00005558185bef8c in ZeroTier::(anonymous namespace)::OneServiceImpl::run (this=0x55581a1b8c00) at service/OneService.cpp:665
#9  0x00005558185eaac0 in _OneServiceRunner::threadMain (this=0x7ffc89e48c10) at one.cpp:1828
#10 0x00005558185e1704 in main (argc=<optimized out>, argv=0x7ffc89e48e08) at one.cpp:2106
```

Per @adamierymenko:
> Looks like this chip lacks SSE4 instructions... so we may need to disable those with compiler flags and only enable them in specific AES functions that are only used with AES extensions... looks like a really old Atom.

## Additional information 

**Desktop (please complete the following information):**
 - OS: Linux
 - ZeroTier Version 1.5.0

**Comment by adamierymenko** [comment]
Fixed in `dev`, maybe try building

**Comment by JeffHenson** [comment]
I've got an older AMD Phenom that doesn't have sse3 and above. Nor does it have AES-NI:

```
$ cat /proc/cpuinfo
<snip>
model name      : AMD Phenom(tm) II X6 1090T Processor
<snip>
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid ape rfmperf pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt cpb hw_pstate vmmcall npt lbrv svm_lock nrip_save pausefilter
<snip>
```

On the dev branch, the selftest fails on the AES benchmarks:

```
$ git show --shortstat HEAD
commit 2c75be0d64772c17c8e39fafd0e8c9daff935485 (HEAD -> dev, origin/dev)
$ ./zerotier-selftest
[info] sizeof(void *) == 8
[info] OSUtils::now() == 1602641175284
[info] hardware concurrency == 6
[info] sizeof(NetworkConfig) == 432160
[other] Testing hex/unhex... PASS
[other] Testing InetAddress encode/decode... 127.0.0.1/9993 feed:dead:babe:dead:beef:f00d:1234:5678/12345
[other] Testing/fuzzing Dictionary... PASS (junk value to prevent optimization-out of test: -19059)
[crypto] getSecureRandom: 4fb742c805b4a77d2dfa3ab6fe74970ed9fb81f0007f29be97922ba8e3c2e9ed8342b0d2d1da7c7222f6b24dc9a0a7b0677204027189678f5ac1f73346828afc
[crypto] getSecureRandom: ec519f4dca1e6a33308378862d22a7e85f1272b3bfa623db23a4fb37345e6a2784a8a65e323994333ec33d6d5677aaf4e516d158ab6dfac5927475a8b55a3fc3
[crypto] getSecureRandom: 77f5e39c105013256d1288f02644b0dc4cac2bff269641a4951792dbdf48c7cbfa7ce3e5d15c5cfe97c6d0f1710648c928e78025523c8961169c9c7969f9b99a
[crypto] Testing Salsa20... PASS
[crypto] Salsa20 SSE: ENABLED
[crypto] Benchmarking Salsa20/12... 419.35 MiB/second (f31ddbcdb3b69d0a5e19ba94a7e2facc)
[crypto] Benchmarking Salsa20/12 fast x64 ASM... 938.235 MiB/second
[crypto] Benchmarking Salsa20/20... 262.379 MiB/second (24c619994ae7f1549136169c9072f3d7)
[crypto] Benchmarking AES-GMAC-SIV... zsh: illegal hardware instruction (core dumped)  ./zerotier-selftest
```

That atleast makes it further than master as that failed on the first benchmark:

```
$ git show --shortstat HEAD
commit fe1ce885a04ae68894b8a8fc1892db212addbf6e (HEAD -> master, tag: 1.5.0, origin/master, origin/HEAD)
$ ./zerotier-selftest
<snip>
[crypto] Testing Salsa20... PASS
[crypto] Salsa20 SSE: ENABLED
[crypto] Benchmarking Salsa20/12... zsh: illegal hardware instruction (core dumped)  ./zerotier-selftest
```

**Comment by TooYoungTooSimp** [comment]
I think maybe provide a non intrinsic (pure software) implementation of some SSE4 instructions is helpful to solve this problem.
My router runs on a old atom which has aes but no sse4. I have to downgrade zt-one to 1.4.6 temporally.

**Comment by glimberg** [comment]
@TooYoungTooSimp there is.  there were just some invalid assumptions of what chips supported what instructions.  Part of what a beta is for :)

**Comment by TooYoungTooSimp** [comment]
@glimberg Great. I've found these code in the dev branch now. Thanks for your excellent work!

**Comment by adamierymenko** [comment]
This should be fixed.
