### ISSUE TITLE
Segmentation fault on LZ4_decompress_safe

### ISSUE THREAD

**Issue by zimbatm** [zerotier/ZeroTierOne#336]
* git commit: 9cc2733ed877faed30154035f0efe95633e88ac2
* OS: Linux/nixos
* Changes: https://gist.github.com/anonymous/2b24fff1f76114e4acd8759c98c470cc

Just changed the Makefile to not strip the program. `make debug` was failing for other reasons.

Compiled using `make` and gcc in the path and then ran in gdb:

```
Reading symbols from ./zerotier-one...done.
(gdb) run
Starting program: /home/zimbatm/code/github.com/zerotier/ZeroTierOne/zerotier-one 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/9xsjqbsldr86vvs7p5ps4qlkjv9dhc0k-glibc-2.23/lib/libthread_db.so.1".
[New Thread 0x7ffff6d81700 (LWP 14889)]
[New Thread 0x7ffff6580700 (LWP 14897)]
[New Thread 0x7ffff5d7f700 (LWP 14898)]
[New Thread 0x7ffff557e700 (LWP 14899)]
[Thread 0x7ffff557e700 (LWP 14899) exited]

Thread 1 "zerotier-one" received signal SIGSEGV, Segmentation fault.
0x000055555555d94d in LZ4_decompress_safe ()
(gdb) bt
#0  0x000055555555d94d in LZ4_decompress_safe ()
#1  0x000055555561210c in ZeroTier::Packet::uncompress() ()
#2  0x00005555555e3f00 in ZeroTier::IncomingPacket::tryDecode(ZeroTier::RuntimeEnvironment const*, bool) ()
#3  0x0000555555628fe7 in ZeroTier::Switch::_handleRemotePacketHead(ZeroTier::InetAddress const&, ZeroTier::InetAddress const&, void const*, unsigned int) ()
#4  0x0000555555629ec5 in ZeroTier::Switch::onRemotePacket(ZeroTier::InetAddress const&, ZeroTier::InetAddress const&, void const*, unsigned int) ()
#5  0x000055555560002d in ZeroTier::Node::processWirePacket(unsigned long, sockaddr_storage const*, sockaddr_storage const*, void const*, unsigned int, unsigned long volatile*) ()
#6  0x000055555564f8bf in ZeroTier::Phy<ZeroTier::(anonymous namespace)::OneServiceImpl*>::poll(unsigned long) [clone .constprop.270] ()
#7  0x0000555555652590 in ZeroTier::(anonymous namespace)::OneServiceImpl::run() ()
#8  0x000055555555a63d in main ()
```

**Comment by adamierymenko** [comment]
Can't reproduce this, and that code hasn't changed in a long time. Is this a clean build?

    make clean
    make ...

**Comment by zimbatm** [comment]
What can I do to help you reproduce the issue? NixOS is a bit unconventional so that might be the issue.
