### ISSUE TITLE
BSD: seg fault at startup with master

### ISSUE THREAD

**Issue by jungle-boogie** [zerotier/ZeroTierOne#514]
Hi All,

Here's the info on the seg fault:
```
$ doas gdb /usr/local/sbin/zerotier-one zerotier-one.core
GNU gdb 6.3
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-unknown-openbsd6.1"...(no debugging symbols found)

Core was generated by `zerotier-one'.
Program terminated with signal 11, Segmentation fault.
Reading symbols from /usr/lib/libpthread.so.23.0...done.
Loaded symbols for /usr/lib/libpthread.so.23.0
Loaded symbols for /usr/local/sbin/zerotier-one
Reading symbols from /usr/local/lib/libestdc++.so.17.0...done.
Loaded symbols for /usr/local/lib/libestdc++.so.17.0
Reading symbols from /usr/lib/libm.so.10.0...done.
Loaded symbols for /usr/lib/libm.so.10.0
Symbols already loaded for /usr/lib/libpthread.so.23.0
Reading symbols from /usr/lib/libc.so.89.5...done.
Loaded symbols for /usr/lib/libc.so.89.5
Reading symbols from /usr/libexec/ld.so...done.
Loaded symbols for /usr/libexec/ld.so
#0  0x00000f2cad78d009 in _rthread_mutex_timedlock (mutexp=0xf2d1f224248, trywait=0, abs=0x0, timed=0) at /usr/src/lib/librthread/rthread_mutex.c:165
165     /usr/src/lib/librthread/rthread_mutex.c: No such file or directory.
        in /usr/src/lib/librthread/rthread_mutex.c
(gdb) bt
#0  0x00000f2cad78d009 in _rthread_mutex_timedlock (mutexp=0xf2d1f224248, trywait=0, abs=0x0, timed=0) at /usr/src/lib/librthread/rthread_mutex.c:165
#1  0x00000f2a9547c913 in ?? () from /usr/local/sbin/zerotier-one
#2  0x0000000000000000 in ?? ()
```

Openbsd devs recently made some changes around rthread_mutex.c:
https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/lib/librthread/rthread_mutex.c?r1=1.3

Is this something you can accommodate?

**Comment by jungle-boogie** [comment]
Possibly unrelated, but this is also happening on FreeBSD -current. I don't have a core dump, though.

Both machines are running the latest git clone of zerotier.

**Comment by jungle-boogie** [comment]
Okay, also happening on freebsd 11.0 -release.
Looks like recent changes to your application is causing the seg fault.

no symbols, but here's some proof:

```
0  0x2125b4be in ?? ()
(gdb) bt
#0  0x2125b4be in ?? ()
#1  0x00000002 in ?? ()
#2  0x0000002f in ?? ()
#3  0x00000076 in ?? ()
#4  0x000000d6 in ?? ()
#5  0x0000007c in ?? ()
#6  0x00000070 in ?? ()
#7  0x00000014 in ?? ()
#8  0x0000000e in ?? ()
#9  0x00000023 in ?? ()
#10 0x00000000 in ?? ()
```

**Comment by jungle-boogie** [comment]
I'm thinking this was a bad install of the binary, which caused the segfaults. I'll close this issue now and if it reoccurs, open it back up.
